# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Meta data
title: 'Kenta Takeshige'
author: ''
description:
  - 'Eastern and Western Woodworking'
  - 'Restoration'

# Site navigation
navigation:
  - title: About
    url: about/
  - title: Works
    url: works/
    subpaginas:
      - subtitle: Creation
        suburl: works-creation/
      - subtitle: Restoration
        suburl: works-restoration/
  - title: Workshop
    url: workshop/
    subpaginas:
      - subtitle: Hand-Tools
        suburl: workshop-hand-tools/
      - subtitle: Finishing-Techniques
        suburl: workshop-finishing-techniques/
  - title: Contact
    url: contact/

# Jekyll settings
permalink: pretty

# Exclude these files from the build process
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml','original_img']
