# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Meta data
url: ""
# url: "https://f-spin.net/k" # the base hostname & protocol for your site
title: 'Kenta Takeshige'
author: ''
description:
  - 'Eastern and Western Woodworking'
  - 'Restoration'

# Site navigation
navigation:
  - title: about
    url: about/
  - title: works
    url: works/
    subpaginas:
      - subtitle: creation
        suburl: works-creation/
      - subtitle: restoration
        suburl: works-restoration/
  - title: workshop
    url: workshop/
    subpaginas:
      - subtitle: hand-tools
        suburl: workshop-hand-tools/
      - subtitle: finishing-techniques
        suburl: workshop-finishing-techniques/
  - title: shop
    url: shop/
    subpaginas:
      - subtitle: eastern
        suburl: shop-eastern/
      - subtitle: western
        suburl: shop-western/
  - title: news
    url: news/
  - title: contact
    url: contact/

# Jekyll settings
permalink: pretty

# Exclude these files from the build process
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml','original_img']
